export enum commonElementTypeKeys {}

export enum contentElementTypeKeys {
    article = 'article',
    aside = 'aside',
    blockquote = 'blockquote',
    body = 'body',
    button = 'button',
    canvas = 'canvas',
    cite = 'cite',
    code = 'code',
    dd = 'dd',
    div = 'div',
    dl = 'dl',
    dt = 'dt',
    em = 'em',
    embed = 'embed',
    fieldset = 'fieldset',
    figcaption = 'figcaption',
    figure = 'figure',
    footer = 'footer',
    form = 'form',
    h1 = 'h1',
    h2 = 'h2',
    h3 = 'h3',
    h4 = 'h4',
    h5 = 'h5',
    h6 = 'h6',
    head = 'head',
    header = 'header',
    label = 'label',
    legend = 'legend',
    main = 'main',
    nav = 'nav',
    li = 'li',
    ol = 'ol',
    ul = 'ul',
    p = 'p',
    pre = 'pre',
    section = 'section',
    small = 'small',
    span = 'span',
    strong = 'strong',
    details = 'details',
    summary = 'summary',
}

export enum elementTypeKeys {
    a = 'a',
    abbr = 'abbr',
    address = 'address',
    area = 'area',
    audio = 'audio',
    b = 'b',
    base = 'base',
    bdl = 'bdl',
    bdo = 'bdo',
    br = 'br',
    caption = 'caption',
    col = 'col',
    colgroup = 'colgroup',
    data = 'data',
    datalist = 'datalist',
    del = 'del',
    dfn = 'dfn',
    dialog = 'dialog',
    hr = 'hr',
    html = 'html',
    i = 'i',
    iframe = 'iframe',
    img = 'img',
    input = 'input',
    ins = 'ins',
    kbd = 'kbd',
    link = 'link',
    map = 'map',
    mark = 'mark',
    meta = 'meta',
    meter = 'meter',
    noscript = 'noscript',
    object = 'object',
    optgroup = 'optgroup',
    option = 'option',
    output = 'output',
    param = 'param',
    picture = 'picture',
    progress = 'progress',
    q = 'q',
    rp = 'rp',
    rt = 'rt',
    ruby = 'ruby',
    s = 's',
    samp = 'samp',
    script = 'script',
    select = 'select',
    source = 'source',
    style = 'style',
    sub = 'sub',
    sup = 'sup',
    svg = 'svg',
    table = 'table',
    tbody = 'tbody',
    td = 'td',
    template = 'template',
    textarea = 'textarea',
    tfoot = 'tfoot',
    th = 'th',
    thead = 'thead',
    time = 'time',
    title = 'title',
    tr = 'tr',
    track = 'track',
    u = 'u',
    var = 'var',
    video = 'video',
    wbr = 'wbr',
}

export enum elementFlexDirectionKeys {
    column = 'column',
    'column-reverse' = 'column-reverse',
    row = 'row',
    'row-reverse' = 'row-reverse',
}

export enum elementFlexAlignContentKeys {
    stretch = 'stretch',
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    'space-between' = 'space-between',
    'space-around' = 'space-around',
    'space-evenly' = 'space-evenly',
    initial = 'initial',
    inherit = 'inherit',
}
export enum elementFlexAlignItemsKeys {
    stretch = 'stretch',
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    baseline = 'baseline',
    initial = 'initial',
    inherit = 'inherit',
}
export enum elementFlexAlignSelfKeys {
    auto = 'auto',
    stretch = 'stretch',
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    baseline = 'baseline',
    initial = 'initial',
    inherit = 'inherit',
}

export enum elementFlexJustifyContentKeys {
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    'space-between' = 'space-between',
    'space-around' = 'space-around',
    'space-evenly' = 'space-evenly',
    initial = 'initial',
    inherit = 'inherit',
}
export enum elementFlexJustifyItemsKeys {
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    baseline = 'baseline',
    initial = 'initial',
    inherit = 'inherit',
}
export enum elementFlexJustifySelfKeys {
    auto = 'auto',
    center = 'center',
    'flex-start' = 'flex-start',
    'flex-end' = 'flex-end',
    baseline = 'baseline',
    initial = 'initial',
    inherit = 'inherit',
}
